// Code generated by ydbgen; DO NOT EDIT.

package main

import (
	"strconv"

	"github.com/ydb-platform/ydb-go-sdk/v3/table"
	"github.com/ydb-platform/ydb-go-sdk/v3/table/resultset"
	"github.com/ydb-platform/ydb-go-sdk/v3/table/types"
)

var (
	_ = strconv.Itoa
	_ = types.StringValue
	_ = table.NewQueryParameters
)

func (u *User) StructValue() types.Value {
	var v0 types.Value
	{
		var v1 types.Value
		{
			vp0 := types.OptionalValue(types.Uint64Value(u.ID))
			v1 = vp0
		}
		var v2 types.Value
		{
			vp0 := types.OptionalValue(types.UTF8Value(u.Name))
			v2 = vp0
		}
		var v3 types.Value
		{
			vp0 := types.OptionalValue(types.Uint32Value(u.Age))
			v3 = vp0
		}
		v0 = types.StructValue(
			types.StructFieldValue("user_id", v1),
			types.StructFieldValue("name", v2),
			types.StructFieldValue("age", v3),
		)
	}
	return v0
}

func (s *Series) Scan(res resultset.Result) (err error) {
	res.ScanWithDefaults(&s.ID, &s.Title, &s.Info, &s.ReleaseDate, &s.Views, &s.UploadedUserID)
	return res.Err()
}

func (s *Series) StructValue() types.Value {
	var v0 types.Value
	{
		var v1 types.Value
		{
			vp0 := types.OptionalValue(types.Uint64Value(s.ID))
			v1 = vp0
		}
		var v2 types.Value
		{
			vp0 := types.OptionalValue(types.UTF8Value(s.Title))
			v2 = vp0
		}
		var v3 types.Value
		{
			vp0 := types.OptionalValue(types.UTF8Value(s.Info))
			v3 = vp0
		}
		var v4 types.Value
		{
			var v5 types.Value
			ok0 := !s.ReleaseDate.IsZero()
			if ok0 {
				v5 = types.OptionalValue(types.DatetimeValueFromTime(s.ReleaseDate))
			} else {
				v5 = types.NullValue(types.TypeDatetime)
			}
			v4 = v5
		}
		var v5 types.Value
		{
			vp0 := types.OptionalValue(types.Uint64Value(s.Views))
			v5 = vp0
		}
		var v6 types.Value
		{
			vp0 := types.OptionalValue(types.Uint64Value(s.UploadedUserID))
			v6 = vp0
		}
		v0 = types.StructValue(
			types.StructFieldValue("series_id", v1),
			types.StructFieldValue("title", v2),
			types.StructFieldValue("series_info", v3),
			types.StructFieldValue("release_date", v4),
			types.StructFieldValue("views", v5),
			types.StructFieldValue("uploaded_user_id", v6),
		)
	}
	return v0
}

func (us UsersList) ListValue() types.Value {
	var list0 types.Value
	vs0 := make([]types.Value, len(us))
	for i0, item0 := range us {
		var v0 types.Value
		{
			var v1 types.Value
			{
				var v2 types.Value
				{
					vp0 := types.OptionalValue(types.Uint64Value(item0.ID))
					v2 = vp0
				}
				var v3 types.Value
				{
					vp0 := types.OptionalValue(types.UTF8Value(item0.Name))
					v3 = vp0
				}
				var v4 types.Value
				{
					vp0 := types.OptionalValue(types.Uint32Value(item0.Age))
					v4 = vp0
				}
				v1 = types.StructValue(
					types.StructFieldValue("user_id", v2),
					types.StructFieldValue("name", v3),
					types.StructFieldValue("age", v4),
				)
			}
			v0 = v1
		}
		vs0[i0] = v0
	}
	if len(vs0) == 0 {
		var t1 types.Type
		{
			var t2 types.Type
			{
				fs0 := make([]types.StructOption, 3)
				var t3 types.Type
				{
					tp0 := types.TypeUint64
					t3 = types.Optional(tp0)
				}
				fs0[0] = types.StructField("user_id", t3)
				var t4 types.Type
				{
					tp0 := types.TypeUTF8
					t4 = types.Optional(tp0)
				}
				fs0[1] = types.StructField("name", t4)
				var t5 types.Type
				{
					tp0 := types.TypeUint32
					t5 = types.Optional(tp0)
				}
				fs0[2] = types.StructField("age", t5)
				t2 = types.Struct(fs0...)
			}
			t1 = t2
		}
		t0 := types.List(t1)
		list0 = types.ZeroValue(t0)
	} else {
		list0 = types.ListValue(vs0...)
	}
	return list0
}

func (ss *SeriesList) Scan(res resultset.Result) (err error) {
	for res.NextRow() {
		var s Series
		res.ScanWithDefaults(&s.ID, &s.Title, &s.Info, &s.ReleaseDate, &s.Views, &s.UploadedUserID)

		if res.Err() == nil {
			*ss = append(*ss, s)
		}
	}
	return res.Err()
}

func (ss SeriesList) ListValue() types.Value {
	var list0 types.Value
	vs0 := make([]types.Value, len(ss))
	for i0, item0 := range ss {
		var v0 types.Value
		{
			var v1 types.Value
			{
				var v2 types.Value
				{
					vp0 := types.OptionalValue(types.Uint64Value(item0.ID))
					v2 = vp0
				}
				var v3 types.Value
				{
					vp0 := types.OptionalValue(types.UTF8Value(item0.Title))
					v3 = vp0
				}
				var v4 types.Value
				{
					vp0 := types.OptionalValue(types.UTF8Value(item0.Info))
					v4 = vp0
				}
				var v5 types.Value
				{
					var v6 types.Value
					ok0 := !item0.ReleaseDate.IsZero()
					if ok0 {
						v6 = types.OptionalValue(types.DatetimeValueFromTime(item0.ReleaseDate))
					} else {
						v6 = types.NullValue(types.TypeDatetime)
					}
					v5 = v6
				}
				var v6 types.Value
				{
					vp0 := types.OptionalValue(types.Uint64Value(item0.Views))
					v6 = vp0
				}
				var v7 types.Value
				{
					vp0 := types.OptionalValue(types.Uint64Value(item0.UploadedUserID))
					v7 = vp0
				}
				v1 = types.StructValue(
					types.StructFieldValue("series_id", v2),
					types.StructFieldValue("title", v3),
					types.StructFieldValue("series_info", v4),
					types.StructFieldValue("release_date", v5),
					types.StructFieldValue("views", v6),
					types.StructFieldValue("uploaded_user_id", v7),
				)
			}
			v0 = v1
		}
		vs0[i0] = v0
	}
	if len(vs0) == 0 {
		var t1 types.Type
		{
			var t2 types.Type
			{
				fs0 := make([]types.StructOption, 6)
				var t3 types.Type
				{
					tp0 := types.TypeUint64
					t3 = types.Optional(tp0)
				}
				fs0[0] = types.StructField("series_id", t3)
				var t4 types.Type
				{
					tp0 := types.TypeUTF8
					t4 = types.Optional(tp0)
				}
				fs0[1] = types.StructField("title", t4)
				var t5 types.Type
				{
					tp0 := types.TypeUTF8
					t5 = types.Optional(tp0)
				}
				fs0[2] = types.StructField("series_info", t5)
				var t6 types.Type
				{
					tp0 := types.TypeDatetime
					t6 = types.Optional(tp0)
				}
				fs0[3] = types.StructField("release_date", t6)
				var t7 types.Type
				{
					tp0 := types.TypeUint64
					t7 = types.Optional(tp0)
				}
				fs0[4] = types.StructField("views", t7)
				var t8 types.Type
				{
					tp0 := types.TypeUint64
					t8 = types.Optional(tp0)
				}
				fs0[5] = types.StructField("uploaded_user_id", t8)
				t2 = types.Struct(fs0...)
			}
			t1 = t2
		}
		t0 := types.List(t1)
		list0 = types.ZeroValue(t0)
	} else {
		list0 = types.ListValue(vs0...)
	}
	return list0
}
